@startuml
'https://plantuml.com/class-diagram


Employee o->ListFunctions
ListFunctions o-> FileFunctions

class FileFunctions {
    + readFile(List<Employee>): List<Employee>
    - parseEmployeeInfo(String[]): Employee
}

class ListFunctions {
    + printList(List<Employee>): void
    - createHeaders(): void
}

class Employee {
    - firstName : String
    - lastName : String
    - salary : int

    + Employee(String, String, int): void
    + getFirstName(): String
    + getLastName(): String
    + getSalary(): int
}

@enduml