@startuml
'https://plantuml.com/class-diagram


HashMapFunctions o-> Content
Content o-> FileFunctions


class FileFunctions {
    + readFile()
}

class HashMapFunctions {
    - wordFreqMap: Map<String, Integer>

    + HashMapFunctions()
    + getWordFreqMap()
    + setKeys()
    + sortMap()
    - isMapSorted()
    - areKeysUnique()
    - swapMaps()
}

class Content{
    + parseContent()
    + printFrequencyDescending()
    + createHistogram()
}


@enduml