@startuml
'https://plantuml.com/class-diagram


App <|-- FileFunctions
App <|-- HashMapFunctions
App <|-- Content

class FileFunctions {
+ readFile()
}

class HashMapFunctions {
+ getWordFreqMap()
+ setKeys()
+ sortMap()
+ swapMaps()
}

class Content{
+ parseContent()
+ printFrequencyDescending()
- createHistogram()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml