@startuml
'https://plantuml.com/class-diagram

FileFunctions o-> DirectoryFunctions
DirectoryFunctions o-> App

class DirectoryFunctions {
    - siteName: String

    + DirectoryFunctions(): void
    + makeDirectory(): String
    + makeJavascriptFolder(): String
    + makeCSSFolder(): String
}

class FileFunctions{
    - html: File
    - siteName: String
    - author: String

    + FileFunctions(String, String): void
    + createHTML(): String
    + writeToHTML(): void
    - formatHTML(): String
}

class App{
    - takeInput(): String
    - parseBoolean(): boolean
    - checkJavascript(): String
    - checkCSS(): String
}

@enduml