@startuml
'https://plantuml.com/class-diagram

ListFunctions o-> FileFunctions

class FileFunctions {
    - input: List
    + FileFunctions()
    + readFile()
}

class ListFunctions {
    - list: List

    + ListFunctions()
    + sortList()
    + printList()
    - formatTable()
}



@enduml