@startuml
'https://plantuml.com/class-diagram

App <|-- FileFunctions
App <|-- ListFunctions

class FileFunctions {
    + readFile()
}

class ListFunctions {
    + sortList()
    + printList()
}

class App {


}


@enduml