@startuml
'https://plantuml.com/class-diagram


App <|-- FileFunctions
FileFunctions <|-- Employee
App <|- ListFunctions

class FileFunctions {
+ readFile()
- parseEmployeeInfo()
}

class ListFunctions {
+ printList()
- createHeaders()
}

class Employee {
firstName : String
lastName : String
salary : int
}

@enduml