@startuml
'https://plantuml.com/class-diagram


Employee o->ListFunctions
ListFunctions o-> FileFunctions

class FileFunctions {
    + readFile()
    - parseEmployeeInfo()
}

class ListFunctions {
    + printList()
    - createHeaders()
}

class Employee {
    - firstName : String
    - lastName : String
    - salary : int

    + getFirstName()
    + getLastName()
    + getSalary()
}

@enduml