@startuml
'https://plantuml.com/class-diagram


HashMapFunctions o-> Content
Content o-> FileFunctions


class FileFunctions {
    + readFile(): String
}

class HashMapFunctions {
    - wordFreqMap: Map<String, Integer>

    + HashMapFunctions(Map<String, Integer>): void
    + getWordFreqMap(): Map<String,Integer>
    + setKeys(String []): boolean
    + sortMap(): boolean
    - isMapSorted(): boolean
    - areKeysUnique(): boolean
    - swapMaps(List<Map.Entry<String,Integer>>): Map<String,Integer>
}

class Content{
    + parseContent(String): String[]
    + printFrequencyDescending(Map<String, Integer>): void
    + createHistogram(int): void
}


@enduml