@startuml
'https://plantuml.com/class-diagram

Inventory o-> Product
JsonFunctions o-> Inventory

class JsonFunctions{
    - inventory: Inventory

    + readJSON()
}

class Inventory{
    - productList: List
    - productMap: HashMap<String, Product>

    + setInventoryMap(productMap)
    + productPresent(query)
    + searchInventory(query)
    - findProduct(key, query)
    - formatProductString(key)
}

class Product{
    - name: String
    - price: double
    - quantity: int

    + getName()
    + getPrice()
    + getQuantity()
}


@enduml