@startuml
'https://plantuml.com/class-diagram

Inventory o-> Product
JsonFunctions o-> Inventory

class JsonFunctions{
    - inventory: Inventory

    + readJSON(): Inventory
}

class Inventory{
    - productList: ArrayList<Product>
    - inventoryMap: HashMap<String, Product>

    + Inventory(ArrayList<Product>): void
    + setInventoryMap(HashMap<String, Product>): void
    + productPresent(String): boolean
    + searchInventory(String): boolean
    + getProductList(): ArrayList<Product>
    - findProduct(String, String): boolean
    - formatProductString(String): String
}

class Product{
    - name: String
    - price: double
    - quantity: int

    + getName(): String
    + getPrice(): double
    + getQuantity(): int
}


@enduml