@startuml
'https://plantuml.com/class-diagram

Inventory o-> Product
JsonFunctions o-> Inventory

class JsonFunctions{
    - inventory: Inventory

    + readJSON()
}

class Inventory{
    - productList: ArrayList<Product>
    - inventoryMap: HashMap<String, Product>

    + setInventoryMap(HashMap<String, Product>)
    + productPresent(String)
    + searchInventory(String)
    + getProductList()
    - findProduct(String, String)
    - formatProductString(String)
}

class Product{
    - name: String
    - price: double
    - quantity: int

    + getName()
    + getPrice()
    + getQuantity()
}


@enduml