@startuml
'https://plantuml.com/class-diagram



 FindWord o-> FileFunctions


class FileFunctions {
    + readFile(): String
    + writeFile(String, String): boolean
}

class FindWord{
    + findAndReplace(String, String, String): String
}

@enduml