@startuml
'https://plantuml.com/class-diagram



 FindWord o-> FileFunctions


class FileFunctions {
    - outputFile: String

    + setOutputFile()
    + readFile()
    + writeFile()
}

class FindWord{
    + findAndReplace()
}

@enduml